# Generated by Django 3.2.7 on 2021-12-13 11:33

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('car_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('car_nombre', models.CharField(max_length=30, verbose_name='Nombre')),
                ('car_descripcion', models.CharField(max_length=150, verbose_name='Descripción')),
            ],
            options={
                'db_table': 'cargo',
            },
        ),
        migrations.CreateModel(
            name='CategoriaArticulo',
            fields=[
                ('cat_art_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('cat_art_nombre', models.CharField(max_length=30, unique=True, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Categoria Articulo',
                'verbose_name_plural': 'Categoria Articulos',
                'db_table': 'categoria_articulo',
                'ordering': ['cat_art_id'],
            },
        ),
        migrations.CreateModel(
            name='CategoriaServicio',
            fields=[
                ('cat_ser_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('cat_ser_nombre', models.CharField(max_length=15, verbose_name='Nombre')),
                ('cat_ser_descripcion', models.CharField(max_length=300, verbose_name='Descripción')),
            ],
            options={
                'db_table': 'categoria_servicio',
            },
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('date_creation', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('dep_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('dep_nombre', models.CharField(max_length=30, verbose_name='Nombre')),
                ('dep_ubicacion', models.CharField(max_length=30, verbose_name='Ubicación')),
                ('slug', models.SlugField(unique=True)),
                ('dep_capacidad', models.PositiveIntegerField(default=0, verbose_name='Capacidad')),
                ('dep_acondicionado', models.BooleanField(default=False, verbose_name='Acondicionado')),
                ('dep_canon_renta', models.PositiveIntegerField(default=0, verbose_name='Renta')),
                ('dep_estado', models.BooleanField(default=False, verbose_name='Disponibilidad')),
                ('dep_costo_mes', models.PositiveIntegerField(default=0, verbose_name='Costo Mensual')),
                ('dep_tipologia', models.CharField(max_length=10, verbose_name='Tipologia')),
                ('dep_piso', models.PositiveIntegerField(verbose_name='Piso')),
                ('dep_imagen_portada', models.ImageField(upload_to='media/departamentos', verbose_name='Portada')),
            ],
            options={
                'db_table': 'departamento',
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('res_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('res_fecha_creacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Creación')),
                ('res_fecha', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Reserva')),
                ('res_estado', models.BooleanField(default=False, verbose_name='Reserva')),
                ('f_use', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'reserva',
            },
        ),
        migrations.CreateModel(
            name='Zona',
            fields=[
                ('zona_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('zona_nombre', models.CharField(max_length=30, verbose_name='Nombre')),
            ],
            options={
                'db_table': 'zona',
            },
        ),
        migrations.CreateModel(
            name='ServicioAdicional',
            fields=[
                ('ser_adi_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('ser_adi_nombre', models.CharField(max_length=300, verbose_name='Nombre')),
                ('ser_adi_precio', models.FloatField(verbose_name='Precio')),
                ('f_cat_ser', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Servicio_Turismo_Real.categoriaservicio')),
            ],
            options={
                'db_table': 'servicio_adicional',
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('pago_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('pago_metodo', models.CharField(choices=[('Paypal', 'Mercado_pago')], max_length=20, verbose_name='Pagos')),
                ('pago_fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Pago')),
                ('pago_efectuado', models.BooleanField(default=False, verbose_name='Pago Realizado')),
                ('pago_monto', models.FloatField()),
                ('pago_respuesta', models.TextField()),
                ('pago_f_res', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Servicio_Turismo_Real.reserva', verbose_name='Pagos')),
            ],
            options={
                'db_table': 'pago',
            },
        ),
        migrations.CreateModel(
            name='Mantenimiento',
            fields=[
                ('man_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('man_fecha_creacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Creación')),
                ('man_fecha_desde', models.DateField(default=datetime.datetime.now, verbose_name='Fecha Desde')),
                ('man_fecha_hasta', models.DateField(default=datetime.datetime.now, verbose_name='Fecha Hasta')),
                ('man_cancelacion', models.BooleanField(verbose_name='Cancelar Mantenimiento')),
                ('man_observacion', models.CharField(max_length=300)),
                ('f_dep', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Servicio_Turismo_Real.departamento')),
            ],
            options={
                'db_table': 'mantenimiento',
            },
        ),
        migrations.CreateModel(
            name='ImagenDepartamento',
            fields=[
                ('ima_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('ima_departamento', models.ImageField(upload_to='media/imagenes_departamentos', verbose_name='Imagenes Departamentos')),
                ('f_dep', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Servicio_Turismo_Real.departamento')),
            ],
            options={
                'db_table': 'imagen_departamento',
            },
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('date_creation', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('fun_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('fun_rut', models.CharField(max_length=10, unique=True, verbose_name='Rut')),
                ('fun_nombre', models.CharField(max_length=30, verbose_name='Nombre')),
                ('fun_apellido_paterno', models.CharField(max_length=30, verbose_name='Apellido Paterno')),
                ('fun_apellido_materno', models.CharField(max_length=30, verbose_name='Apellido Materno')),
                ('f_car', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Servicio_Turismo_Real.cargo', verbose_name='Cargo')),
                ('user_creation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='servicio_turismo_real_funcionario_creation', to=settings.AUTH_USER_MODEL)),
                ('user_updated', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='servicio_turismo_real_funcionario_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'funcionario',
            },
        ),
        migrations.CreateModel(
            name='DetalleCostoDepartamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('des_cos_fecha_ingreso', models.DateTimeField(auto_now=True)),
                ('des_cos_dep_dia', models.IntegerField(default=0, verbose_name='Costo Diario')),
                ('des_cos_dep_semanal', models.IntegerField(default=0, verbose_name='Costo Semanal')),
                ('pf_fun', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Servicio_Turismo_Real.funcionario')),
            ],
            options={
                'db_table': 'detalle_costo_departamento',
            },
        ),
        migrations.AddField(
            model_name='departamento',
            name='f_zona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Servicio_Turismo_Real.zona', verbose_name='Zona'),
        ),
        migrations.AddField(
            model_name='departamento',
            name='user_creation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='servicio_turismo_real_departamento_creation', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='departamento',
            name='user_updated',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='servicio_turismo_real_departamento_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='CostoDepartamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cos_mensual', models.IntegerField(default=0)),
                ('cos_cant', models.IntegerField(default=0)),
                ('cos_subtotal', models.IntegerField(default=0)),
                ('dep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Servicio_Turismo_Real.departamento')),
                ('des_cos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Servicio_Turismo_Real.detallecostodepartamento')),
            ],
            options={
                'db_table': 'costo_departamento',
            },
        ),
        migrations.CreateModel(
            name='CheckOut',
            fields=[
                ('check_out_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('check_out_fecha', models.DateTimeField(auto_now=True, verbose_name='Fecha')),
                ('check_out_observacion', models.CharField(max_length=300, verbose_name='Observación')),
                ('check_out_multas', models.PositiveIntegerField(default=0, verbose_name='Multas')),
                ('f_fun', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Servicio_Turismo_Real.funcionario')),
                ('f_res', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Servicio_Turismo_Real.reserva')),
            ],
            options={
                'db_table': 'check_out',
            },
        ),
        migrations.CreateModel(
            name='CheckIn',
            fields=[
                ('check_in_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('check_in_fecha', models.DateTimeField(auto_now=True, verbose_name='Fecha')),
                ('chek_in_observacion', models.CharField(max_length=300, verbose_name='Observación')),
                ('f_fun', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Servicio_Turismo_Real.funcionario')),
                ('f_res', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Servicio_Turismo_Real.reserva')),
            ],
            options={
                'db_table': 'check_in',
            },
        ),
        migrations.CreateModel(
            name='Carro',
            fields=[
                ('carro_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('carro_cantidad', models.PositiveIntegerField(default=1, verbose_name='Cantidad de Dias')),
                ('carro_f_dep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Servicio_Turismo_Real.departamento')),
                ('carro_f_res', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='Servicio_Turismo_Real.reserva')),
            ],
            options={
                'db_table': 'carro',
            },
        ),
        migrations.CreateModel(
            name='ArticuloDepartamento',
            fields=[
                ('date_creation', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('art_dep_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('art_dep_fecha_ingreso', models.DateTimeField(auto_now=True)),
                ('art_dep_nombre', models.CharField(max_length=30, verbose_name='Nombre')),
                ('art_dep_estado', models.BooleanField(verbose_name='Estado')),
                ('art_dep_precio', models.PositiveIntegerField(default=0, verbose_name='Precio')),
                ('f_cat_art', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Servicio_Turismo_Real.categoriaarticulo', verbose_name='Categoria')),
                ('user_creation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='servicio_turismo_real_articulodepartamento_creation', to=settings.AUTH_USER_MODEL)),
                ('user_updated', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='servicio_turismo_real_articulodepartamento_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Articulo Departamento',
                'verbose_name_plural': 'Articulos Departamentos',
                'db_table': 'articulo_departamento',
                'ordering': ['art_dep_id'],
            },
        ),
        migrations.CreateModel(
            name='InventarioDepartamento',
            fields=[
                ('pf_dep', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='Servicio_Turismo_Real.departamento')),
                ('inv_dep_cantidad', models.FloatField(verbose_name='Cantidad')),
                ('inv_dep_costo', models.IntegerField(verbose_name='Costo')),
                ('pf_art_dep', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Servicio_Turismo_Real.articulodepartamento')),
            ],
            options={
                'db_table': 'inventario_departamento',
                'unique_together': {('pf_dep', 'pf_art_dep')},
            },
        ),
        migrations.CreateModel(
            name='DetalleServicioAdicional',
            fields=[
                ('det_ser_fecha', models.DateTimeField(auto_now=True, verbose_name='Fecha')),
                ('det_ser_total', models.IntegerField(verbose_name='Total')),
                ('pf_res', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='Servicio_Turismo_Real.reserva')),
                ('pf_ser_adi', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Servicio_Turismo_Real.servicioadicional')),
            ],
            options={
                'db_table': 'detalle_servicio_adicional',
                'unique_together': {('pf_res', 'pf_ser_adi')},
            },
        ),
    ]
